/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package beans.enumerators;

/**
 * This class handles enumerators related with SCC_F_032
 *
 * @author SANTOS
 */
public enum SCC_F_032Enum {

    institucion_salud,
    historia_clinica,
    primer_apellido,
    segundo_apellido,
    primer_nombre,
    segundo_nombre,
    tipo_identificacion_victima,
    numero_identificacion_victima,
    medida_edad,
    edad_paciente,
    sexo_paciente,
    ocupacion_paciente,
    aseguradora,
    desplazado,
    discapacitado,
    grupo_etnico,
    otro_grupo_etnico,
    departamento_residencia,
    municipio_residencia,
    barrio_residencia_victima,
    direccion_residencia,
    telefono_residencia,
    barrio_evento,
    direccion_evento,
    dia_evento,
    mes_evento,
    año_evento,
    fecha_evento,
    dia_semana_evento,
    hora_evento,
    minuto_evento,
    am_pm,
    hora_militar_evento,
    dia_consulta,
    mes_consulta,
    año_consulta,
    fecha_consulta,
    dia_semana_consulta,
    hora_consulta,
    minuto_consulta,
    am_pm1,
    hora_militar_consulta,
    remitido,
    de_que_ips,
    intencionalidad,
    otra_intencionalidad,
    lugar_ocurrio_lesion,
    otro_lugar,
    activida_que_realizaba,
    otra_actividad,
    mecanismo_objeto_lesion,
    altura,
    polvora_cual,
    tipo_desastre_natural,
    otro_tipo_mecanismo_objeto_lesion,
    uso_alcohol,
    uso_drogas,
    grado_mas_grave_quemadura,
    porcentaje_cuerpo_quemado,
    tipo_transporte_lesionado,
    tipo_transporte_contraparte,
    otro_tipo_transporte_usuario,
    otro_tipo_transporte_contraparte,
    tipo_usuario_transporte,
    otro_tipo_de_usuario,
    uso_elementos_seguridad,
    usaba_cinturon,
    usaba_casco_motocicleta,
    usaba_casco_bicicleta,
    usaba_chaleco,
    otro_elemento_seguridad,
    cual_otro_elemento,
    cual_otro_tipo_agresor,
    cual_otro_tipo_maltrato,
    antecedentes_previos_agresion,
    relacion_agresor_victima,
    contexto_en_violencia_interpersonal,
    otro_tipo_relacion_victima,
    sexo_agresores,
    intento_previo_autoinflingida,
    antecedentes_transtorno_mental,
    factores_precipitantes,
    otro_factor_precipitante,
    sitio_anatomico_sistemico,
    naturaleza_lesion_laceracion,
    sitio_anatomico_craneo,
    naturaleza_lesion_cortada,
    sitio_anatomico_afectado_ojos,
    naturaleza_lesion_profunda,
    sitio_anatomico_maxilofacial,
    naturaleza_lesion_esgince,
    sitio_anatomico_cuello,
    naturaleza_lesion_fractura,
    sitio_anatomico_torax,
    naturaleza_lesion_quemadura,
    sitio_anatomico_abdomen,
    naturaleza_lesion_contusion,
    sitio_anatomico_columna,
    naturaleza_lesion_organo_sitemica,
    sitio_anatomico_pelvis,
    naturaleza_lesion_trauma_craneoencefalico,
    sitio_anatomico_miembros_superiores,
    naturaleza_lesion_otro_tipo,
    sitio_anatomico_miembros_inferiores,
    naturaleza_lesion_cual_otro,
    sitio_anatomico_otro,
    naturaleza_lesion_no_se_sabe,
    sitio_anatomico_cual_otro,
    maltrato_fisico,
    agresor_padre,
    maltrato_psicologico,
    agresor_madre,
    maltrato_abuso_sexual,
    agresor_padrastro,
    maltrato_negligencia,
    agresor_madrastra,
    maltrato_abandono,
    agresor_conyuge,
    maltrato_institucional,
    agresor_hermano,
    maltrato_sin_dato,
    agresor_hijo,
    agresor_otro,
    agresor_sin_dato,
    destino_paciente,
    otro_destino_paciente,
    CIE_1,
    CIE_2,
    CIE_3,
    CIE_4,
    medico_diligencio_ficha,
    digitador_ficha,
    fecha_nacimiento,
    NOVALUE;

    /**
     * converts a string to an enumerator, if not possible then returns NOVALUE
     *
     * @param str
     * @return
     */
    public static SCC_F_032Enum convert(String str) {
        try {
            return valueOf(str);
        } catch (IllegalArgumentException ex) {
            return NOVALUE;
        }
    }
}
